apiVersion: v1
kind: Service
metadata:
  name: nextjsmongoapp
spec:
  selector:
    app: nextjsmongoapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjsmongoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjsmongoapp
  template:
    metadata:
      labels:
        app: nextjsmongoapp
    spec:
      containers:
        - name: app
          image: nextjs-docker-app:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/somedb
          imagePullPolicy: Never
